<!-- Navbar -->
  <div class=" ">
    <nav class="navbar navbar-expand-md container  " data-bs-theme="dark">
      <div class="container-fluid ">
        <a href="#" class="navbar-brand ">
          <h2 class="text-secondary">Matt Nandavong</h2>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class=" justify-items-center collapse navbar-collapse justify-content-end "
          id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
            <li class="nav-item "><a href="about.html" class="nav-link">About Me</a></li>
            <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
            <li class="nav-item"><a href="projects.html" class="nav-link">Projects</a></li>
            <!-- <li class="nav-item"><a href="./public/hobbies.html" class="nav-link">Hobbies</a></li> -->
          </ul>

        </div>

      </div>

    </nav>
  </div>